### ISSUE TITLE
Nested API routing conflicts 

### ISSUE THREAD

**Issue by kennethacohen** [bmvantunes/youtube-2020-july-next-api-routes-next-connect#1]
Hey @bmvantunes! Great demo + video. This approach was super clean.

I'm running into an issue extending on this that I wanted to raise (I'm assuming others have maybe run into it too!).

**The issue**
Nested routes are returning the wrong results if you hit one after another. For example, if you go to `/api/champions` => `/api/champions/:id` => `/api/champions`, you will get correct results on the first two calls, but the third will actually be calling the second route and is expecting an id, which throws an error.

This doesn't seem to happen when you import `next-connect` separately into each API route.

I modified this repo with the change here:
https://github.com/kennethacohen/repro-next-routing-bug

**Comment by bmvantunes** [comment]
In order for those scenarios to work together just return the handler as a function and invoke it where you need :)

I committed in the repo those changes if you want to have a look: https://github.com/bmvantunes/youtube-2020-july-next-api-routes-next-connect/commit/e9a42a85725cdd3ca70eba6795768dc4ff6a9332

**Comment by bmvantunes** [comment]
you can also have (if you prefer) this on each file
```
import handler from '.....'
import nextConnect from 'next-connect'

export default nextConnect().use(handler).get(.......)
```

**Comment by kennethacohen** [comment]
Ah makes sense! Thank you!!

**Comment by bmvantunes** [comment]
@kennethacohen you are welcome my friend =)

I'm honestly in love with next-connect at this stage =D

**Comment by kennethacohen** [comment]
Agreed! And thank you for the great demos 😄
